### ISSUE TITLE
A network error (such as timeout, interrupted connection or unreachable host) has occurred.

### ISSUE THREAD

**Issue by kalvinchang** [kalvinfromcode/aftermath#5]
Clicking login button with validated email and password displays "A network error (such as timeout, interrupted connection or unreachable host) has occurred."

**Comment by DarienTsai** [comment]
is there actually an account existing yet

**Comment by kalvinchang** [comment]
No, which is why the console should display the error "There is no user record corresponding to this email." This error indicates that Firebase was reached at least, but not even this is happening right now.

**Comment by kalvinchang** [comment]
Error fixed by replacing <div> with <form>. The 2 <input> tags will have to be styled differently.
